version: '3.8'

services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: bdexemple
      MARIADB_USER: usuari
      MARIADB_PASSWORD: contrasenya
    volumes:
      - ./mariadb_data:/var/lib/mysql

  apache-php:
    build: ./html  # en lloc de "image: php:8.1-apache"
    container_name: apache-php
    restart: always
    volumes:
      - ./html:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    environment:
      MYSQL_HOST: mariadb
      MYSQL_USER: usuari
      MYSQL_PASSWORD: contrasenya
      MYSQL_DATABASE: bdexemple

volumes: {}
